# This rule is not used by the project kubedeck itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ctrl.nikcorp.ru.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubedeck
    app.kubernetes.io/managed-by: kustomize
  name: kubedeck-admin-role
rules:
- apiGroups:
  - ctrl.nikcorp.ru
  resources:
  - kubedecks
  verbs:
  - '*'
- apiGroups:
  - ctrl.nikcorp.ru
  resources:
  - kubedecks/status
  verbs:
  - get
